#!/bin/bash
# Deployment Setup Script

echo "🚀 UXplore Flask - Deployment Setup"
echo "===================================="
echo ""

# Generate SECRET_KEY
SECRET_KEY=$(python -c 'import secrets; print(secrets.token_urlsafe(32))')

echo "Generated SECRET_KEY: $SECRET_KEY"
echo ""
echo "📋 Configuration Steps:"
echo ""
echo "1. Copy this SECRET_KEY to your environment variables:"
echo "   SECRET_KEY=$SECRET_KEY"
echo ""
echo "2. For Render.com:"
echo "   - Go to render.com/dashboard"
echo "   - Create new Web Service from GitHub"
echo "   - Set Environment Variables:"
echo "     * SECRET_KEY=$SECRET_KEY"
echo "     * RESEND_API_KEY=<your-resend-key>"
echo "     * RESEND_FROM_EMAIL=noreply@uxplores.com"
echo "     * ADMIN_PASSWORD=<secure-password>"
echo "   - Add PostgreSQL database"
echo ""
echo "3. For Railway.app:"
echo "   - Go to railway.app/dashboard"
echo "   - Create new GitHub project"
echo "   - Add PostgreSQL from marketplace"
echo "   - Set Environment Variables:"
echo "     * SECRET_KEY=$SECRET_KEY"
echo "     * RESEND_API_KEY=<your-resend-key>"
echo "     * RESEND_FROM_EMAIL=noreply@uxplores.com"
echo "     * ADMIN_PASSWORD=<secure-password>"
echo ""
echo "✅ Configuration files created:"
echo "   ✓ Procfile"
echo "   ✓ runtime.txt"
echo "   ✓ requirements.txt (updated with gunicorn)"
echo "   ✓ render.yaml"
echo "   ✓ railway.toml"
echo "   ✓ Dockerfile"
echo "   ✓ docker-compose.yml"
echo "   ✓ .dockerignore"
echo "   ✓ .env.example"
echo "   ✓ DEPLOYMENT.md"
echo ""
echo "📖 Read DEPLOYMENT.md for detailed instructions"
